### ISSUE TITLE
collection not found for module path: turnstile/lang/lang/reader

### ISSUE THREAD

**Issue by sorawee** [wilbowma/cur#96]
When I tried `raco pkg install https://github.com/wilbowma/cur.git\#turnstile-core`, I get 

```
standard-module-name-resolver: collection not found
  for module path: turnstile/lang/lang/reader
  collection: "turnstile/lang/lang"
```

Turnstile should be added to `info.rkt` in `turnstile-core` branch.

**Comment by sorawee** [comment]
There are also more errors even after installing `turnstile`. Most of them is about how `~Type` is invalid in `syntax-parse`. I think I'm gonna give up for now.

**Comment by wilbowma** [comment]
Weird. Must have broken something in my last refactor. thanks for trying!

--

**Comment by wilbowma** [comment]
Try the following installation procedure:
```
> raco pkg install https://github.com/stchang/macrotypes.git?path=macrotypes-lib#cur
> raco pkg install https://github.com/stchang/macrotypes.git?path=turnstile-lib#cur
> raco pkg install https://github.com/wilbowma/cur.git?path=cur-lib#turnstile-core
```

`turnstile-lib` is already in info.rkt, so not sure how you got that first error. My guess would be something isn't up-to-date in the documentation. I can't reproduce the second error.

I've confirmed that issue #95 is fixed in that branch.

**Comment by stchang** [comment]
> not sure how you got that first error

You cant `raco pkg install` from the repository root since it's not a package. You'd have to target the `cur` directory, eg https://github.com/stchang/cur/tree/turnstile-core/cur

**Comment by stchang** [comment]
Oops, replace `stchang` with `wilbowma` in the link above.

**Comment by stchang** [comment]
Actually, forget what I wrote. It still wont work bc `cur-lib` will still fetch from `master`. You have to manually install like in https://github.com/wilbowma/cur/issues/96#issuecomment-525850434.

**Comment by sorawee** [comment]
Yup, it works now! Thanks to both of you :)
